### PR TITLE
Added lookup of XRP/USD exchange via Bitstamp and display under balances

### PR DESCRIPTION
**Pull request by xulture**
Hi guys,

I've added Bitstamp and USD conversion only.  I can't seem to find reliable non-rate-limited and updated throughout the day service for forex between USD and various local currencies.  It'd be nice to give the user ability to select what fifa currency to display.

This is what it looks like:
image

I've tested it also with live wallet, everything appears to be in order but I haven't done transfers.

As you suggested, it would be nice to also allow user to select what crypto exchange to get exchange rate from, but I haven't done that because of variety of API's and number of other exchanges to pick from.

Do we need to check with Bitstamp if they mind using their pubic API for conversion?

Perhaps I could look into displaying current balance in #tabpayments together with title of the account; in the dropdown,  and we could use (already fetched) exchange rate to display under the amount field as the user types the amount.

Cheers,

### CODE REVIEW

**Comment by ToastWallet** [comment]
Hi xulture! Thanks for taking the time. We do need a feature like this however we'd prefer it queried the exchange rate directly from the Ripple network through ripple-lib. As you know Ripple is a distributed ledger. It should be possible to query the order book on the ledger for an array of trusted USD IOUs and average these to give a figure. This also means we wouldn't need to be doing XHRs off to a third party.

We're only doing bug fixes at the moment not feature adds but if you update your pull request as per the above we may well use it for next major revision.

**Comment by xulture** [comment]
Thanks! I'll look into it.  Bitstamp is one of their IOUs for USD, but we may as well let user pick any other currency that ripple-lib provides.

**Comment by ToastWallet** [comment]
Good idea. But the ability to change the IOUs that are being displayed should be hidden away in a settings menu item. By default we should just average Gatehub and Bitstamp and whatever other trusted IOUs there are. Definitely do not average all IOUs for a given currency as all IOUs are not equally good credit.

**Comment by xulture** [comment]
I can't find it.  Newer versions of ripple-lib offer ability to request OrderBook with the list of current orders Account has created, but nothing in relation to 'last price' or current bid/ask on the network; as far as I understand. :-(

**Comment by ToastWallet** [comment]
Hey, we've updated ripple-lib and written in the USD balance feature using the bitstamp orderbook on the ripple network. Thanks for your suggestion!

**Pull request closed without merging**
